spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/helloSpring
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true  #JPA가 생성하는 SQL을 출력한다.
    hibernate:
      ddl-auto: none  #JPA는 테이블을 자동으로 생성하는 기능을 제공하는데 none 를 사용하면 해당 기능을 끔, create -> 엔티티 기반으로 자동 생성